import React from 'react';
import Head from 'next/head';
import Sidebar from '../sidebar';
import Profile from '../profile';

type LayoutProps = {
  children: React.ReactNode;
};

export const Layout = ({ children }: LayoutProps) => {
  return (
    <>
      <Head>
        <title>Shadowy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-screen h-screen flex">
        <Sidebar />
        <Profile />
        {children}
      </div>
    </>
  );
};

export default Layout;
