import React from 'react';
import Head from 'next/head';
import { signIn } from 'next-auth/react';
import Sidebar from '../sidebar';
import { useGithubContext } from '@/contexts/github-context';

type LayoutProps = {
  children: React.ReactNode;
};

export const Layout = ({ children }: LayoutProps) => {
  const { user } = useGithubContext();
  return (
    <div className="relative">
      <Head>
        <title>Shadowy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!user && (
        <div className="w-full h-full absolute flex justify-center items-center z-10">
          <div className="text-center p-4 bg-gray-800 rounded-xl space-y-4">
            <p>We couldn't authentify you.</p>
            <p>Please sign-in to your Github account</p>
            <button className="btn btn-secondary" onClick={() => signIn('github')}>
              Sign in
            </button>
          </div>
        </div>
      )}
      <div className={`w-screen h-screen flex ${!user ? 'blur-md' : ''}`}>
        <Sidebar />
        {children}
      </div>
    </div>
  );
};

export default Layout;
