import type { NextPage } from 'next';
import Head from 'next/head';
import { useSession, signIn } from 'next-auth/react';

const Home: NextPage = () => {
  const { data: session } = useSession();
  console.log('hehe', session);
  return (
    <div>
      <Head>
        <title>Shadowy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Hello</h1>
        <button onClick={() => signIn('github')}>Connect</button>
      </main>
    </div>
  );
};

export default Home;
